spring.application.name=energy
# ---spring.datasource.url=jdbc:postgresql://localhost:5432/energy
# spring.datasource.username=postgres
# spring.datasource.password=nika
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA Configuration ---
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=5000MB
spring.servlet.multipart.max-request-size=5000MB

# --- Database connection (Neon) ---
spring.datasource.url=jdbc:postgresql://ep-odd-wildflower-a4u6z2e4-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require&preferQueryMode=simple&reWriteBatchedInserts=true
&tcpKeepAlive=true
spring.datasource.username=neondb_owner
spring.datasource.password=npg_OwG5YeibD2pm
server.port=8082

# Connection pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=1740000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

spring.datasource.hikari.keepaliveTime=120000


# --- JPA & Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
 # use 'update' only for quick dev; 'validate' when Flyway manages schema
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# --- Flyway (DB migrations) ---
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Root logger ? only show errors (suppresses Spring/Hibernate info/debug)
logging.level.root=ERROR

# Disable Hibernate SQL logging
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF

# Disable Spring framework internal logging
logging.level.org.springframework=ERROR
logging.level.org.springframework.web=ERROR
logging.level.org.springframework.web.servlet=ERROR
logging.level.org.springframework.web.multipart.support=ERROR

# Enable logs for your package (replace with your actual package)
logging.level.com.example.energy=INFO

# Keep multipart enabled
spring.servlet.multipart.enabled=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.id.optimizer.pooled.preferred=true
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG


# --- JWT ---
app.jwt.secretBase64=mQ9k3Vq2fLZ8RjYt8YbXr0gPp6Hc2VwKxTz9aN5sU1dE4fGhJ7kLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsT==
app.jwt.expirationMinutes=720